name: 'Download Premake'
description: 'A premake downloader for GitHub CI, made to be simple to use. To run use "uses: BEASTSM96/premake-action", in your CI file.'
runs:
  using: 'node12'
  main: 'index.js'
