name: CI Linux (Ubuntu)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Premake downloader
        uses: ./ --premake=beta1

      - name: Run Premake
        run: premake5 --version