name: CI Windows

on: [push]

jobs:
  build:
    runs-on: macos-latest
    name: CI Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Premake downloader
        uses: ./premake

      - name: Run Premake
        run: premake5 --help